# Generated by Django 5.2.1 on 2026-06-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_answer_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
